version: "3.9"
services:

  db:
    container_name: postgres_container
    image: postgres:latest
    env_file:
      db/.env
    volumes:
      - ./db/initDB:/docker-entrypoint-initdb.d
      - ~/.ps_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G